name: Update IP List

on:
  schedule:
    - cron: '0 */1 * * *'  # 每1小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:  # 允许提交触发 (如果需要)

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 chardet
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py
      
    - name: Commit and push changes
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        git remote set-url origin https://${{ env.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push origin HEAD:${{ github.ref }}
        else
          echo "No changes detected, skipping commit."
        fi
